account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # reset password urls
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),
    path('register/', views.register, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "blog"


urlpatterns = [
    # path("home", views.home, name="home")
    path("", views.postlist, name ="bloglist"),
    path("<int:year>/<int:month>/<int:day>/<slug>/", views.postdetail , name="post_detail")
    
]

home/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "home"


urlpatterns = [
    path("", views.home, name="home"),
    path('searchs/', views.search, name='search'),
]

myblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace="account")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
 
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django import forms
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class Mypost(models.Model):
    STATUS_CHOICES = (

        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='my_posts')
    image = models.ImageField(upload_to='image/%Y/%m/%d',
                              blank=True)
    detail=RichTextUploadingField()
    files = models.FileField(upload_to='file/%Y/%m/%d', blank=True)
    
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default="draft")

home/forms.py
from django import forms
from .models import Mypost


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)



class PostForm(forms.ModelForm):
    class Meta:
        model = Mypost
        fields = ('title', 'image', 'detail', 'files', )

home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from home.forms import SearchForm
from django.db.models import Avg, Count, Q, F
from blog.models import Post
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from .forms import PostForm
from .models import Mypost

# def simple_upload(request):
  
#     return render(request, 'home/index.html')

# Create your views here.


def home(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'home/index.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, "home/index.html", {})


# def home(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             data = Mypost()  # create relation with model
#             data.title = form.cleaned_data['title']
#             data.image = form.cleaned_data['image']
#             current_user = request.user
#             data.author_id = current_user.id
#             data.detail = form.cleaned_data['detail']
#             data.files = form.cleaned_data['files']
           
#             data.save() 
#             form.save()
#             return redirect('/')
#     else:
#         form = PostForm()
#     return render(request, "home/index.html", {
#         'form': form
#     })


def search(request):
    if request.method == 'POST': # check post
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query'] # get form input data
            posts = Post.objects.filter(title__icontains=query)

            
            context = {'posts': posts, 'query':query,
                        }
            return render(request, 'home/search.html', context)

    return HttpResponseRedirect('/')

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://localhost/blog-static/css/style.css">
    

    <title>Document</title>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-dark my-nav">
  <a class="navbar-brand" href="/">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:bloglist' %}">Blog</a>
      </li>

      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
        </li>

      

        {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:login' %}">Login/Signup</a>
      </li>

      {% endif %}
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
  
    </ul>
    <form class="form-inline my-2 my-lg-0" action=" {% url 'home:search' %} " method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" name="query" placeholder="Search" aria-label="Search">
      
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


{% block content %}



{% endblock content %}




    







<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}

{% load crispy_forms_tags %}
{% block content %}

<br><br><br>
 <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %} 
{% comment %} 
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Submit</button>
  </form>

  <p><a href="{% url 'blog:bloglist' %}">Return to home</a></p> {% endcomment %}


{% endblock content %}

home/templates/home/search.html
{% extends 'home/base.html' %}

{% block content %}

    
<div class="container" style="margin-top:120px; margin-bottom:60px;">
    <div class="row">

            <div class="col-xl-12">
                <div class="card card-body bg-light">

                       <h2>Post containing "{{ query }}"</h2>
                <h3>
                {% with posts.count as total_results %}
                    Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
                </h3>

            <div class="row mt-3">
             {% for post in posts %}

            <div class="card ml-5" style="width: 19rem;">
                 <a href="{{ post.get_absolute_url }}">
                            <img src="{% if post.image %}{{ post.image.url }} {% else %}  http://localhost/external-css/img/no_image.png {% endif %}" class="card-img-top" alt="...">
                        </a>
                <div class="card-body my-product">
                    <h5 class="card-title text-center"><a href="{{ post.get_absolute_url }}" >{{ post.title }}</a></h5>
                    <p class="card-text text-center">{{ post.detail | safe | truncatewords:30 }}</p>
                    {% comment %} <p class="text-center"><a href="{{ product.get_absolute_url }} " class="site-btn btn-line">SHOP NOW</a></p> {% endcomment %}
                </div>
            </div>
             {% empty %}
                <h5 class="ml-3">There are no results for your query.</h5>
            {% endfor %}
             </div>
           

                </div>
            </div>  
    </div>
</div>

{% endblock content %}